#!/bin/bash
for FILE in `find | grep "\.md$"`; do
    echo "baking" $FILE;
    DIR=$(dirname $FILE);
    BASE=$(echo $DIR | sed -e 's#/[^/]\+#/..#g');
    CSS_FILE=$(echo $BASE/css/main.css);

    pandoc \
        --standalone \
        --smart \
        --css=$CSS_FILE \
        --include-in-header=./header/responsive.html \
        $FILE \
        -o ${FILE%.md}.html;
done
