#!/bin/bash
for FILE in `find | grep "\.md$"`; do
    echo "baking" $FILE;
    DIR=$(dirname $FILE);
    BASE=$(echo $DIR | sed -e 's#/[^/]\+#/..#g');
    CSS_FILE=$(echo $BASE/css/main.css);

    pandoc \
        --standalone \
        --smart \
        --css=$CSS_FILE \
        --to=html5 \
        --highlight-style=monochrome \
        --template ./template.html \
        $FILE \
        -o ${FILE%.md}.html;
done

pandoc \
    --standalone \
    --smart \
    --css="./css/main.css" \
    --to=html5 \
    --highlight-style=monochrome \
    --template ./index_template.html \
    index.md \
    -o index.html;
